=== UUUUnotfound/dd-git/UCMDBPython/src/config/mapping_schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by me (home) -->
<!--W3C Schema generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="mappings">
		<xs:annotation>
			<xs:documentation>Root element which can contain single mapping definition</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ci" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="parserClassName" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="com.hp.ucmdb.discovery.library.communication.downloader.cfgfiles.CiMappingConfigFile"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ci">
		<xs:annotation>
			<xs:documentation>This element describes what data to take from external source and how to modify this data in order to receive CI instance of this particular type</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="map" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="map">
		<xs:annotation>
			<xs:documentation>Describes mapping between particular external source item and particular CI attribute. External source item can be for example column in database table or property name in property file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="attribute" type="xs:string" default="ciName"/>
				<xs:element name="column">
					<xs:complexType mixed="true">
						<xs:attribute name="type" type="xs:string" default="string"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="converter" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="converter">
		<xs:annotation>
			<xs:documentation>Converter which is used to convert data taken from external source to appropriate value of CI attribute. Value of this element is simply method name in Python script which should be invoked in order to convert data. Module name is Python script name</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="module" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UUUUnotfound/dd-git/UCMDBPython/src/config/mapping_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\mapping_schema.xsd" parserClassName="com.hp.ucmdb.discovery.library.communication.downloader.cfgfiles.CiMappingConfigFile">
	<ci type="ip">
		<map>
			<attribute>ip_address</attribute>
			<column>0</column>
		</map>
		<map>
			<attribute>ip_domain</attribute>
			<column>1</column>
		</map>
		<map>
			<attribute>ip_dnsname</attribute>
			<column>2</column>
		</map>
	</ci>
</mappings>
