=== UUUUnotfound/dd-git/UCMDBPython/src/config/ScannersConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Genadi Rabinovich (Mercury Interactive) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="scanners-configuration">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="platform" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="parserClassName" type="xs:string" use="required" fixed="com.hp.ucmdb.discovery.library.communication.downloader.cfgfiles.platform.scanners.ScannersByPlatformConfigurationFile"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="platform">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="scanner-deployment"/>
				<xs:element ref="scanner-upgrade" minOccurs="0"/>
				<xs:element ref="scanner-execution" minOccurs="0"/>
				<xs:element ref="platform-recognition"/>
				<xs:element ref="os-commands" minOccurs="0"/>
				<xs:element ref="additional-properties" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="display-name" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-deployment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="basedir-name" minOccurs="0"/>
				<xs:element ref="file-separator" minOccurs="0"/>
				<xs:element ref="basedir" minOccurs="0"/>
				<xs:element ref="scanner-remote-executable-name" minOccurs="0"/>
				<xs:element ref="scanner-remote-executable-path" minOccurs="0"/>
				<xs:element ref="scanner-remote-configfile-name" minOccurs="0"/>
				<xs:element ref="scanner-remote-configfile-path" minOccurs="0"/>
				<xs:element ref="scanner-executable" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="scanner-pre-scan-script-local-file" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="scanner-post-scan-script-local-file" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="scanner-pre-scan-script-remote-file" minOccurs="0"/>
                <xs:element ref="scanner-post-scan-script-remote-file" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-upgrade">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="scanner-check-version-command" minOccurs="0"/>
				<xs:element ref="scanner-check-version-pattern" minOccurs="0"/>
				<xs:element ref="scanner-version" minOccurs="0"/>
				<xs:element ref="pre-upgrade-commands" minOccurs="0"/>
				<xs:element ref="post-upgrade-commands" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-execution">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="run-scanner-cmd"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="platform-recognition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="platform-identification-commands" minOccurs="0"/>
				<xs:element ref="platform-aliases" minOccurs="0"/>
				<xs:element ref="platform-architectures" minOccurs="0"/>
				<xs:element ref="platform-default-architecture" minOccurs="0"/>
                <xs:element ref="platform-unsupported-architectures" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="additional-properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dir"/>
	<xs:element name="basedir-name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dir"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="basedir">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dir"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="executable"/>
	<xs:element name="scanner-remote-executable-name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="executable"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="separator"/>
	<xs:element name="file-separator">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="separator"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="path"/>
	<xs:element name="scanner-remote-executable-path">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="path"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name"/>
	<xs:element name="scanner-remote-configfile-name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-pre-scan-script-local-file">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
			</xs:sequence>
            <xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-post-scan-script-local-file">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
			</xs:sequence>
            <xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-pre-scan-script-remote-file">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-post-scan-script-remote-file">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="scanner-remote-configfile-path">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="path"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="command"/>
	<xs:element name="scanner-check-version-command">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pattern"/>
	<xs:element name="scanner-check-version-pattern">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pattern"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="version"/>
	<xs:element name="scanner-version">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="version"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pre-upgrade-commands">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-upgrade-commands">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="rename-command">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command"/>
				<xs:element ref="parameter" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="copy-command">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter"/>
	<xs:element name="delete-command">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command"/>
				<xs:element ref="parameter" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="chmod-command">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command"/>
				<xs:element ref="parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="os-commands">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="delete-command"/>
				<xs:element ref="rename-command"/>
				<xs:element ref="copy-command"/>
				<xs:element ref="chmod-command"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="run-scanner-cmd">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="platform-identification-commands">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="command" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property-value"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="property-value"/>
	<xs:element name="scanner-executable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="executable"/>
			</xs:sequence>
			<xs:attribute name="architecture" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="alias"/>
	<xs:element name="platform-aliases">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="alias" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="platform-default-architecture">
		<xs:complexType>
			<xs:attribute name="display-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="architecture">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="display-name" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="platform-architectures">
		<xs:complexType>
			<xs:sequence>
                <xs:element ref="architecture" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="default" type="xs:string" use="optional"/>
        </xs:complexType>
	</xs:element>
    <xs:element name="platform-unsupported-architectures">
        <xs:complexType>
      	    <xs:sequence>
      			<xs:element ref="alias" maxOccurs="unbounded"/>
      		</xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== UUUUnotfound/dd-git/UCMDBPython/src/config/ScannersConfigurationByPlatform.xml
<scanners-configuration parserClassName="com.hp.ucmdb.discovery.library.communication.downloader.cfgfiles.platform.scanners.ScannersByPlatformConfigurationFile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./ScannersConfiguration.xsd">
	<!--All missed properties for specific platform will be taken from "all" platform.-->
	<!--Each property can be specified for platform per architecture-->
	<!--
		This section dedicated to scanner deployment.
	-->
	<platform name="all">
		<scanner-deployment>
			<basedir-name>
				<dir>discagnt</dir>
			</basedir-name>
			<file-separator>
				<separator>/</separator>
			</file-separator>
			<!-- Agents option which specifies where to place scanner and scanner configuration file. Used for UD Agent compatibility-->
			<basedir>
				<dir>~/.VAR{basedir-name}VAR{file-separator}</dir>
			</basedir>
			<!-- Scanner executable name on remote machine-->
			<scanner-remote-executable-name>
				<executable>scan</executable>
			</scanner-remote-executable-name>
			<!-- Full path of scanner executable -->
			<scanner-remote-executable-path>
				<path>VAR{basedir}VAR{scanner-remote-executable-name}</path>
			</scanner-remote-executable-path>
			<!-- Scanner executable name on remote machine-->
			<scanner-remote-configfile-name>
				<name>scan.cxz</name>
			</scanner-remote-configfile-name>
			<!-- Full path of scanner configuration file -->
			<scanner-remote-configfile-path>
				<path>VAR{basedir}VAR{scanner-remote-configfile-name}</path>
			</scanner-remote-configfile-path>
            <scanner-pre-scan-script-remote-file>
                <name>prescan.sh</name>
            </scanner-pre-scan-script-remote-file>
            <scanner-post-scan-script-remote-file>
                <name>postscan.sh</name>
            </scanner-post-scan-script-remote-file>
		</scanner-deployment>
		<!-- This section defines properties for scanner upgrade process.
			Based on scanner-check-version property we get scanner banner and using
			scanner-check-version-pattern property we can obtain scanner version on remote machine
			and compare it with scanner-version property.
			Use pre-upgrade-commands and post-upgrade-commands properties for execution commands
			before and after upgrade.
		-->
		<scanner-upgrade>
			<!-- Commands to be executed before scanner upgrade-->
			<pre-upgrade-commands>
				<command>mkdir VAR{basedir}</command>
			</pre-upgrade-commands>
			<!-- Commands to be executed after scanner upgrade-->
			<post-upgrade-commands>
				<command>chmod 600 VAR{scanner-remote-configfile-path}</command>
				<command>chmod 700 VAR{scanner-remote-executable-path}</command>
			</post-upgrade-commands>
		</scanner-upgrade>
		<!--
			This section specifies command for running scanner.
		-->
		<scanner-execution>
			<!-- Command for running scanner. In script we first execute "cd BASEDIR" -->
			<run-scanner-cmd>
				<command>nohup sh -c '.VAR{file-separator}VAR{scanner-remote-executable-name} -home:VAR{basedir}.. -cfg:VAR{scanner-remote-configfile-name} -l:local.xsf -appliance &amp;';  echo ''; sleep 5</command>
			</run-scanner-cmd>
		</scanner-execution>
		<!--
			This section defined properties used for platform and architecture identification.
			platform-identification-command - which command should be executed by client.
			Based on the output of this command we can identify platform and architecture
			using platform-aliases and platform-architectures properties.
		-->
		<platform-recognition>
			<!-- Commands to identify platform and architecture -->
			<platform-identification-commands>
                <command>ver</command>
                <command>reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" /v PROCESSOR_ARCHITECTURE</command>
                <command>echo BREAKOP4WIN</command>
                <command>uname -s</command>
                <command>uname -p</command>
                <command>uname -m</command>
            </platform-identification-commands>
		</platform-recognition>
		<os-commands>
			<delete-command>
				<command>rm</command>
				<parameter>-f</parameter>
			</delete-command>
			<rename-command>
				<command>mv</command>
			</rename-command>
			<copy-command>
				<command>cp</command>
			</copy-command>
			<chmod-command>
				<command>chmod</command>
				<parameter>640</parameter>
			</chmod-command>
		</os-commands>
		<additional-properties>
			<property name="property_name1" architecture="sparc">
				<property-value>property_value1</property-value>
			</property>
			<property name="property_name2">
				<property-value>property_value2</property-value>
			</property>
		</additional-properties>
	</platform>
	<platform name="windows" display-name="Windows">
		<scanner-deployment>
			<file-separator>
				<separator>\</separator>
			</file-separator>
			<!-- Agents option which specifies where to place scanner and scanner configuration file. Used for UD Agent compatibility
				Currently it is current directory-->
			<basedir>
				<dir>%SystemRoot%VAR{file-separator}</dir>
			</basedir>
			<!-- Scanner executable name on remote machine-->
			<scanner-remote-executable-name>
				<executable>scan.exe</executable>
			</scanner-remote-executable-name>
			<!-- Scanner executable for this platform -->
            <scanner-executable architecture="x86">
                <executable>scanwin-x86.exe</executable>
            </scanner-executable>
            <scanner-executable architecture="amd64">
                <executable>scanwin-x64.exe</executable>
            </scanner-executable>
            <scanner-pre-scan-script-local-file>
                <name>win32-x86.prescan.cmd</name>
            </scanner-pre-scan-script-local-file>
            <scanner-post-scan-script-local-file>
                <name>win32-x86.postscan.cmd</name>
            </scanner-post-scan-script-local-file>
            <scanner-pre-scan-script-remote-file>
                <name>prescan.cmd</name>
            </scanner-pre-scan-script-remote-file>
            <scanner-post-scan-script-remote-file>
                <name>postscan.cmd</name>
            </scanner-post-scan-script-remote-file>
		</scanner-deployment>
		<scanner-upgrade>
			<!-- Commands to be executed after scanner upgrade-->
			<post-upgrade-commands/>
		</scanner-upgrade>
		<scanner-execution>
			<!-- Command for running scanner -->
			<run-scanner-cmd>
				<!-- Command for running scanner. In script we first execute "cd BASEDIR" -->
				<command>start .VAR{file-separator}VAR{scanner-remote-executable-name} -cfg:VAR{scanner-remote-configfile-name} -l:local.xsf -appliance</command>
			</run-scanner-cmd>
		</scanner-execution>
		<platform-recognition>
			<platform-aliases>
				<alias>windows</alias>
				<alias>winnt</alias>
				<alias>cygwin</alias>
			</platform-aliases>
            <platform-architectures default="x86">
                <architecture display-name="x86">x86</architecture>
                <architecture display-name="x64">amd64</architecture>
            </platform-architectures>
			<platform-default-architecture display-name="x86" />
		</platform-recognition>
		<os-commands>
			<delete-command>
				<command>del</command>
			</delete-command>
			<rename-command>
				<command>move</command>
			</rename-command>
			<!--On windows we want to copy hidden files (/H) and suppress confirmation (/Y) and override read-only files (/R)-->
			<copy-command>
				<command>xcopy</command>
				<parameter>/H</parameter>
				<parameter>/Y</parameter>
				<parameter>/R</parameter>
			</copy-command>
			<chmod-command>
				<command>attrib</command>
				<parameter>-R</parameter>
				<parameter>-S</parameter>
				<parameter>-H</parameter>
			</chmod-command>
		</os-commands>
	</platform>
    <platform name="unix" display-name="All Unix">
        <scanner-deployment>
            <scanner-pre-scan-script-local-file>
                <name>all-unix.prescan.sh</name>
            </scanner-pre-scan-script-local-file>
            <scanner-post-scan-script-local-file>
                <name>all-unix.postscan.sh</name>
            </scanner-post-scan-script-local-file>
        </scanner-deployment>
        <platform-recognition/>
    </platform>
	<platform name="solaris" display-name="Solaris">
		<scanner-deployment>
			<basedir>
				<dir>$HOME/.VAR{basedir-name}VAR{file-separator}</dir>
			</basedir>
			<!-- Scanner executable for this platform -->
			<scanner-executable architecture="sparc">
				<executable>scansolaris-sparc</executable>
			</scanner-executable>
			<scanner-executable architecture="i86pc">
				<executable>scansolaris-x86</executable>
			</scanner-executable>
            <scanner-pre-scan-script-local-file architecture="sparc">
                <name>solaris-sparc.prescan.sh</name>
            </scanner-pre-scan-script-local-file>
            <scanner-pre-scan-script-local-file architecture="i86pc">
                <name>solaris-x86.prescan.sh</name>
            </scanner-pre-scan-script-local-file>
            <scanner-post-scan-script-local-file architecture="sparc">
                <name>solaris-sparc.postscan.sh</name>
            </scanner-post-scan-script-local-file>
            <scanner-post-scan-script-local-file architecture="i86pc">
                <name>solaris-x86.postscan.sh</name>
            </scanner-post-scan-script-local-file>
		</scanner-deployment>
		<platform-recognition>
            <platform-identification-commands>
				<command>uname -s</command>
				<command>uname -m</command>
			</platform-identification-commands>
			<platform-aliases>
				<alias>solaris</alias>
				<alias>sunos</alias>
			</platform-aliases>
			<platform-architectures default="i86pc">
				<architecture display-name="SPARC">sparc</architecture>
